config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'post#index' , as: 'home'
    get 'about'=>'pages#about',as:'about'
  resources :post do
    resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comment
    # more details http://guides.rubyonrails.org/active_record_validations.html
    validates :title,presence: true , length: { minimum: 5 ,
                                        too_short: "%{count} too small length" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    http_basic_authenticate_with name: "yogesh",password:"1234",only:[:destroy]
    def create 
        @post = Post.find(params[:post_id])
        @comment = @post.comment.create(comment_params)
        redirect_to(post_path(@post))
    end 

    private def comment_params
        params.require(:comment).permit(:username,:body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        @title = 'About us';
    end     
end

app/controllers/post_controller.rb
class PostController < ApplicationController
    http_basic_authenticate_with name: "yogesh",password:"1234",except:[:index,:show]
    def index
        @post = Post.all
    end
    def new
        @post = Post.new
    end 

    def create 
        #render plain:params[:post].inspect
        @post = Post.new(post_params)
        if( @post.save )
            redirect_to @post
        else 
            render 'new'
        end    

    end     
    
    def edit 
        @post = Post.find(params[:id])
    end  
        
    def update
        @post = Post.find(params[:id])
        if(@post.update(post_params))
            redirect_to @post
        else 
            render 'edit'
        end    

    end 

    private def post_params
        params.require(:post).permit(:title,:body)
    end  

    def show 
        @post = Post.find(params[:id])
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy

        redirect_to posts_path
    end    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/comments/_comments.html.erb
<h3>comments</h3>
<% @post.comment.each do |c| %>
<div class="row">
    <div class="col-sm-12 my-2">
            <div class="card card-body bg-light">
                <strong><%= c.username %></strong><%= c.body %>
                <%= link_to  "X", post_path(c.post),
                        method: :delete,
                        data:{ confirm: 'Are you sure ?' }
                         %>
            </div>
        </div>
    </div>
<% end %>

app/views/comments/_form.html.erb
<h3>Add Comment </h3>

<%= form_for([@post,@post.comment.build]) do |f| %>
    <p>
        <%= f.label :username %></br>
        <%= f.text_field(:username, {:class => 'form-control'})%>
    </p>
    <p>
        <%= f.label :body %><br>
        <%= f.text_area( :body, {:class => 'form-control'})    %>
    </p>
    <p>
        <%= f.submit({:class => 'btn btn-primary'}) %>
    </p>
<% end %>    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleBlog</title>
    <%= csrf_meta_tags %>
     <%= stylesheet_link_tag    "default", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "default", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag  "https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"   %>
     <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Playfair+Display:700,900" %>
  </head>

  <body>
   <div class="container">
        <div class="nav-scroller py-1 mb-2">
          <nav class="navbar bg-dark navbar-dark navbar-expand-sm" ">
              <a class="navbar-brand" href="#">SimpleBlog</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar navbar-nav">
                  <li class="nav-item"><%= link_to("Home", home_path, {:class => 'nav-link'}) %> </li>
                  
                </ul>
                <ul class="navbar navbar-nav ml-auto">
                  <li class="nav-item"><%= link_to("Create Post",new_post_path , {:class => 'nav-link'}) %> </li>
                  
                </ul>
              </div>  
          </nav>
        </div>
         <%= yield %>
    </div>  
  </body>
</html>

app/views/pages/about.html.erb
<h1><%=@title  %></h1>

app/views/post/edit.html.erb
<h1>Edit Post </h1>
<%= form_for :post, url: post_path(@post) , method: :patch   do |f| %>
   <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>    
   <% end %>
    <p>
        <%= f.label :title %></br>
        <%= f.text_field(:title, {:class => 'form-control'})%>
    </p>
    <p>
        <%= f.label :body %><br>
        <%= f.text_area( :body, {:class => 'form-control'})    %>
    </p>
    <p>
        <%= f.submit({:class => 'btn btn-primary'}) %>
    </p>
<% end %>   

app/views/post/index.html.erb
<h1>Blog Posts </h1>

<% @post.each do |post| %>
<div class="row">
    <div class="col-sm-12 my-2">
            <div class="card card-body bg-light">
                <h2><%= post.title %></h2>
                <p><%= post.body %> </p>
                <%= link_to  "Read More", post_path(post), :class => 'btn btn-default text-left' %>
            </div>
        </div>
    </div>
<% end %>

app/views/post/new.html.erb
<h1>Add Post </h1>
<%= form_for :post, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
   <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>    
   <% end %>
    <p>
        <%= f.label :title %></br>
        <%= f.text_field(:title, {:class => 'form-control'})%>
    </p>
    <p>
        <%= f.label :body %><br>
        <%= f.text_area( :body, {:class => 'form-control'})    %>
    </p>
    <p>
        <%= f.submit({:class => 'btn btn-primary'}) %>
    </p>
<% end %>    

app/views/post/show.html.erb
<h2><%= @post.title %> </h2>
<p><%= @post.body %></p> 
 <%= link_to  "Edit", edit_post_path(@post), :class => 'btn btn-info' %>
  <%= link_to  "Delete", post_path(@post),
                        method: :delete,
                        data:{ confirm: 'Are you sure ?' }, 
                        :class => 'btn  btn-danger' %>
<hr>

<%= render "comments/comments" %>
<%= render "comments/form" %>